language: python
dist: xenial
os: linux
virtualenv:
  system_site_packages: false
jobs:
  fast_finish: true
  include:
  - env: DISTRIB="conda" PYTHON_VERSION="3.7" COVERAGE="true"
install:
- source tests/travis_install.sh
before_script:
- git config --global user.email "wusher@kth.com"
- git config --global user.name "Will Usher"
script:
- python setup.py install
- pytest
- |
  if [[ "$COVERAGE" == "true" ]]; then
    pre-commit install
    pre-commit run --files src
  fi
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
- travis-cleanup
cache:
  pip: true
  directories:
  - "$HOME/miniconda"
notifications:
  email: false
deploy:
  edge: true
  provider: pypi
  username: __token__
  password:
    secure: pVkeKwp1YSOakhs9537zc9X1CxajMoAL84/YTIOEZs5sEpc71q17RN8KDDbXaaZoFvYqQnZTc2a2pJhyYaOzykgJs0oVf4rPLSUpMPx/UpZDe9R/zThOyD6etVMV8078CK9YTXzNcK1cAxKBwyrg0NdTKHFuYOPwqhgsC6MPJ/x7ndSdKSNOctChlsJDvgJ2UaoFCMMMG9692bzdUEiT2FDl7gP9YQc5Xc7aWA/g003GwIRUA86RmgeVIKgdXvkNAZKGELHC3AXuJIBs5n84pNRcycLCvsYECWgihd80kZd+bH0ONpDSsvpC3lRJtlsB8l/0FR/byzZIDxPIpUviRt8ndyMyPbLZepWn18fsVHcGLcxygJ5XJUpePdDywZ09W/PYcznobQpSFxpAw/vLIde0Hmuw2+SEhtDtLgCaojqBl5g9FQtooorZjgE6yVHdr+WPnqdo8IYWH+VutMoybqVhnmM2vVT0RkhSVGXRJ7z34/jyZu96LD7DXY0aELVoBPpwvYYYKZ1s0dzQqiqOJgJXhqg6n5gubjMgmsz0Ixjz+6lVg9d0o2nLAA1QgO3BG8ewJtYWudBp1Y5JrcggXzOVWJC+F9EadkR+kCdCGOE3DOfBQ7HbZLy4hRpM6xT8IGwiJ4wifBN5mOe129hip11GJeQlLbrXy9x4FNr2vHc=
  on:
    tags: true
    all_branches: true
  cleanup: false
